export const lightTheme = {
  color: {
    bgHotels: '#f3e0db',
    bgFooter: '#904a37',
    secondary: '#efbfad',
  },
  backgroundHeader: {
    margin: '0px auto',
    padding: '51px 104px 120px 104px',
    background: 'url(/images/bg_header_light.jpg)',
    backgroundSize: 'cover',
    color: '#FFFFFF',
  },
  logo: {
    image: 'url(/images/logo_white.svg)',
  },
  typography: {
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    h1: {
      fontSize: '50px',
      lineHeight: '59px',
      fontWeight: 500,
      textAlign: 'left',
      margin: '0px 0px 100px',
      color: '#FFFFFF',
    },
    h2: {
      fontSize: '40px',
      lineHeight: '47px',
      fontWeight: 500,
      textAlign: 'center',
      paddingTop: '120px',
      paddingBottom: '105px',
      margin: 0,
      color: '#383838',
    },
    h3: {
      fontSize: '40px',
      lineHeight: '47px',
      fontWeight: 500,
      paddingBottom: '50px',
      margin: 0,
      color: '#343008',
    },
    label: {
      lineHeight: '21px',
      fontWeight: 400,
      fontSize: '18px',
      marginBottom: '24px',
      paddingLeft: '24px',
      display: 'block',
      boxSizing: 'border-box',
    },
    button: {
      background: '#d47e5f',
      color: '#ffffff',
    },
    describtionName: {
      fontWeight: 500,
      fontSize: '24px',
      lineHeight: '28px',
      color: '#343008',
    },
    describtionPlace: {
      fontWeight: 400,
      fontSize: '24px',
      lineHeight: '28px',
      color: '#d47e5f',
    },
  },
}

export const darkTheme = {
  color: {
    bgHotels: '#EAF0F9',
    bgFooter: '#10367C',
    secondary: '#cddcf1',
  },
  backgroundHeader: {
    margin: '0px auto',
    padding: '51px 104px 120px 104px',
    background: 'url(/images/bg_header.svg)',
    backgroundSize: 'cover',
    color: '#FFFFFF',
  },
  logo: {
    image: 'url(/images/logo.svg)',
  },
  typography: {
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    h1: {
      fontSize: '50px',
      lineHeight: '59px',
      fontWeight: 500,
      textAlign: 'left',
      margin: '0px 0px 100px',
      color: '#FFFFFF',
    },
    h2: {
      fontSize: '40px',
      lineHeight: '47px',
      fontWeight: 500,
      textAlign: 'center',
      paddingTop: '120px',
      paddingBottom: '105px',
      margin: 0,
      color: '#383838',
    },
    h3: {
      fontSize: '40px',
      lineHeight: '47px',
      fontWeight: 500,
      paddingBottom: '50px',
      margin: 0,
      color: '#0e254a',
    },
    label: {
      lineHeight: '21px',
      fontWeight: 400,
      fontSize: '18px',
      marginBottom: '24px',
      paddingLeft: '24px',
      display: 'block',
      boxSizing: 'border-box',
    },
    button: {
      background: '#3077c6',
      color: '#ffffff',
    },
    describtionName: {
      fontWeight: 400,
      fontSize: '24px',
      lineHeight: '28px',
      color: '#3077c6',
    },
    describtionPlace: {
      fontWeight: 400,
      fontSize: '24px',
      lineHeight: '28px',
      color: '#bfbfbf',
    },
  },
}
