export const lightTheme = {
  color: {
    generalWhite: '#FFFFFF',
    generalBlack: '#383838',
    bgHotels: '#f3e0db',
    bgFooter: '#904a37',
    bgDescribtion: '#efbfad',
    primaryText: '#343008',
    secondaryText: '#d47e5f',
  },
  bgHeader: {
    margin: '0px auto',
    padding: '3% 5% 10%',
    background: 'url(/images/bg_header_light.jpg)',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    color: '#FFFFFF',
  },
  logo: {
    image: 'url(/images/logo_white.svg)',
  },
  actions: {
    hover: {
      opacity: 0.7,
      cursor: 'pointer',
    },
  },
  typography: {
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    mobile: {
      fontSize: '28px',
      lineHeight: '33px',
      textAlign: 'center',
      color: '#383838',
    },
    h1: {
      fontSize: '50px',
      lineHeight: '59px',
      fontWeight: 500,
      textAlign: 'left',
    },
    h2: {
      fontSize: '40px',
      lineHeight: '47px',
      fontWeight: 500,
      textAlign: 'center',
      color: '#383838',
    },
    label: {
      lineHeight: '21px',
      fontWeight: 400,
      fontSize: '18px',
      marginBottom: '24px',
      paddingLeft: '24px',
      display: 'block',
      boxSizing: 'border-box',
    },
    button: {
      fontWeight: 500,
      fontSize: '24px',
      lineHeight: '28px',
      textAlign: 'center',
      background: '#d47e5f',
      color: '#ffffff',
      borderRadius: '8px',
      cursor: 'pointer',
      border: 'none',
    },
    describtionName: {
      fontWeight: 500,
      fontSize: '24px',
      lineHeight: '28px',
      color: '#343008',
    },
    describtionPlace: {
      fontWeight: 400,
      fontSize: '24px',
      lineHeight: '28px',
      color: '#d47e5f',
    },
    a: {
      fontWeight: 400,
      fontSize: '24px',
      lineHeight: '28px',
      textDecoration: 'none',
    },
  },
}

export const darkTheme = {
  color: {
    generalWhite: '#FFFFFF',
    generalBlack: '#383838',
    bgHotels: '#EAF0F9',
    bgFooter: '#10367C',
    bgDescribtion: '#cddcf1',
    primaryText: '#3077c6',
    secondaryText: '#bfbfbf',
  },
  bgHeader: {
    margin: '0px auto',
    padding: '3% 7% 10%',
    background: 'url(/images/bg_header.svg)',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    color: '#FFFFFF',
  },
  logo: {
    image: 'url(/images/logo.svg)',
  },
  actions: {
    hover: {
      opacity: 0.7,
      cursor: 'pointer',
    },
  },
  typography: {
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    mobile: {
      fontSize: '28px',
      lineHeight: '33px',
      textAlign: 'center',
      color: '#383838',
    },
    h1: {
      fontSize: '50px',
      lineHeight: '59px',
      fontWeight: 500,
      textAlign: 'left',
    },
    h2: {
      fontSize: '40px',
      lineHeight: '47px',
      fontWeight: 500,
      textAlign: 'center',
      color: '#383838',
    },
    label: {
      lineHeight: '21px',
      fontWeight: 400,
      fontSize: '18px',
      marginBottom: '24px',
      paddingLeft: '24px',
      display: 'block',
      boxSizing: 'border-box',
    },
    button: {
      fontWeight: 400,
      fontSize: '24px',
      lineHeight: '28px',
      textAlign: 'center',
      background: '#3077c6',
      color: '#ffffff',
      borderRadius: '8px',
      cursor: 'pointer',
      border: 'none',
    },
    describtionName: {
      fontWeight: 500,
      fontSize: '24px',
      lineHeight: '28px',
      color: '#3077c6',
    },
    describtionPlace: {
      fontWeight: 400,
      fontSize: '24px',
      lineHeight: '28px',
      color: '#bfbfbf',
    },
    a: {
      fontWeight: 400,
      fontSize: '24px',
      lineHeight: '28px',
      textDecoration: 'none',
    },
  },
}
